
line-length = 79
exclude = ["tests/", "*/migrations/", ".venv/", "env/"]

[lint]
extend-select = [
    "D",
    "A",
    "B0",
    "E",
    "I",
    "N",
    "Q",
    "W",
    "UP",
    "ERA",
    "ANN",
    "FIX",
    "C90",
    "RUF",
]
ignore = [
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D203",
    "D213",
    "N806",
    "N813",
    "N818",
    "D213",
    "ANN002",
    "ANN003",
    "RUF001",
    "RUF002",
    "RUF003",
]
preview = true

[lint.extend-per-file-ignores]
"settings.py" = ["E501"]
"models.py" = ["D105", "D106"]

[lint.mccabe]
max-complexity = 10

[lint.isort]
combine-as-imports = true
known-first-party = ["core", "blog", "pages", "blogicum"]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "single"
